# scrcpy_device/_constants.py
"""Protocol constants for scrcpy 3.x"""

# Control message types (client -> server)
TYPE_INJECT_KEYCODE = 0
TYPE_INJECT_TEXT = 1
TYPE_INJECT_TOUCH_EVENT = 2
TYPE_INJECT_SCROLL_EVENT = 3
TYPE_BACK_OR_SCREEN_ON = 4
TYPE_EXPAND_NOTIFICATION_PANEL = 5
TYPE_EXPAND_SETTINGS_PANEL = 6
TYPE_COLLAPSE_PANELS = 7
TYPE_GET_CLIPBOARD = 8
TYPE_SET_CLIPBOARD = 9
TYPE_SET_DISPLAY_POWER = 10
TYPE_ROTATE_DEVICE = 11
TYPE_UHID_CREATE = 12
TYPE_UHID_INPUT = 13
TYPE_UHID_DESTROY = 14
TYPE_OPEN_HARD_KEYBOARD_SETTINGS = 15
TYPE_START_APP = 16
TYPE_RESET_VIDEO = 17

# Device message types (server -> client)
DEVICE_MSG_TYPE_CLIPBOARD = 0
DEVICE_MSG_TYPE_ACK_CLIPBOARD = 1
DEVICE_MSG_TYPE_UHID_OUTPUT = 2

# Actions for key and touch events
ACTION_DOWN = 0
ACTION_UP = 1
ACTION_MOVE = 2
ACTION_CLICK = 2  # for BACK_OR_SCREEN_ON

# Get clipboard copy key
COPY_KEY_NONE = 0
COPY_KEY_COPY = 1
COPY_KEY_CUT = 2

# Display power mode
DISPLAY_POWER_OFF = 0
DISPLAY_POWER_ON = 1

# Mouse pointer ID (64-bit signed -1)
SC_POINTER_ID_MOUSE = -1

# Pressure encoding
MAX_PRESSURE = 0xFFFF  # maps 1.0 -> 0xFFFF

# Scroll encoding (range -16.0 .. 16.0)
MAX_SCROLL = 32767  # maps 16.0 -> 32767

# Video stream flags
FLAG_CONFIG = 1 << 63
FLAG_KEY_FRAME = 1 << 62
PTS_MASK = FLAG_KEY_FRAME - 1

# Codec IDs
CODECS = {
    0x68323634: "h264",
    0x68323635: "hevc",
    0x00617631: "av1",
}

# Video header size
HEADER_SIZE = 12

# Keycode map (partial, add more as needed)
KEYCODE_HOME = 3
KEYCODE_BACK = 4
KEYCODE_APP_SWITCH = 187
KEYCODE_MENU = 82
KEYCODE_POWER = 26
KEYCODE_VOLUME_UP = 24
KEYCODE_VOLUME_DOWN = 25
KEYCODE_ENTER = 66
KEYCODE_DEL = 67
KEYCODE_TAB = 61
KEYCODE_SPACE = 62
KEYCODE_DPAD_UP = 19
KEYCODE_DPAD_DOWN = 20
KEYCODE_DPAD_LEFT = 21
KEYCODE_DPAD_RIGHT = 22